name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Setup SSH
      run: |
        # Create the StallMate.pem file from the secret and set the correct permissions
        echo "${{ secrets.EC2_SSH_KEY }}" > StallMate.pem
        chmod 400 StallMate.pem

    # Step 3: Check EC2 instance connectivity
    - name: Check EC2 instance connectivity
      run: |
        ssh -o StrictHostKeyChecking=no -i StallMate.pem ubuntu@ec2-13-215-252-79.ap-southeast-1.compute.amazonaws.com uptime

    # Step 4: Deploy to EC2
    - name: Deploy code to EC2
      run: |
        ssh -i StallMate.pem ubuntu@ec2-13-215-252-79.ap-southeast-1.compute.amazonaws.com "cd /home/ubuntu/StallMate && git pull && source ~/.nvm/nvm.sh && sh run.sh"